services:
  web:
    image: ghcr.io/sekai-soft/pill-city:latest
    container_name: pill-city
    restart: unless-stopped
    # env_file:
    #   - env
    depends_on:
      - mongodb
      - redis
  # worker:
  #   image: ghcr.io/sekai-soft/pill-city:latest
  #   restart: unless-stopped
  #   entrypoint: /home/app/entrypoint-worker.sh
  #   env_file:
  #     - env
  #   depends_on:
  #     - mongodb
  #     - redis
  # beat:
  #   image: ghcr.io/sekai-soft/pill-city:latest
  #   restart: unless-stopped
  #   entrypoint: /home/app/entrypoint-beat.sh
  #   env_file:
  #     - env
  #   depends_on:
  #     - mongodb
  #     - redis
  mongodb:
    image: mongo:8.2
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  mongodb_data:
  redis_data:
